version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dpd
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  cache:
    image: redis:6.2-alpine
    restart: always
    network_mode: "host"
    volumes: 
      - /data

  qcdocker:
    container_name: dpd_docker
    network_mode: "host"
    restart: always
    working_dir: /dpd-zero
