version: "3"

services:
  qcdocker:
    container_name: dpd_docker
    ports:
      - "9000:9000"
    networks:
      - dpd_network
    restart: always
    depends_on: 
      - db
    build:
      context: .

    working_dir: /dpd-zero

  db:
    image: mariadb
    restart: always
    networks:
      - dpd_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dpd
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  dpd_network:
    driver: bridge